# import = [
#     "%APPDATA%/alacritty/alacritty-theme/themes/catppuccin_mocha.toml",
# ]
# i give up

shell = "pwsh"

[window]
# opacity = 1.00
opacity = 0.96
dimensions = { columns = 107, lines = 38 }
# position = {x = 100, y = 70}
dynamic_title = false
# dynamic_padding = true

[font]
normal = {family = "Hack Nerd Font Mono", style = "Regular"}
size = 12

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]

[keyboard]
bindings = [
    # Copy to clipboard (Ctrl + Shift + C)
    { key = "C", mods = "Control|Shift", action = "Copy" },

    # Paste from clipboard (Ctrl + Shift + V)
    { key = "V", mods = "Control", action = "Paste" },

    # Open a new window (Ctrl + Shift + N)
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },

    # Toggle fullscreen (F11)
    { key = "F11", action = "ToggleFullscreen" },

    # Increase Font Size (Ctrl + Plus)
    { key = "Plus", mods = "Control", action = "IncreaseFontSize" },

    # Decrease Font Size (Ctrl + Minus)
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" }
]

# Theme
[colors]
transparent_background_colors = true

[colors.primary]
background = '#282c34'
foreground = '#dcdfe4'

[colors.cursor]
text = '#1E1E2E'
cursor = '#D9D9D9'

[colors.selection]
text = '#e0def4'
background = '#403d52'

[colors.normal]
black = '#282c34'
red = '#e06c75'
green = '#98c379'
yellow = '#e5c07b'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#5a6374'

[colors.bright]
black = '#282c34'
red = '#e06c75'
green = '#98c379'
yellow = '#e5c07b'
blue = '#61afef'
magenta = '#c678dd'
cyan = '#56b6c2'
white = '#dcdfe4'
