[window]
# opacity = 1.00
opacity = 0.96
dimensions = { columns = 107, lines = 38 }
# position = {x = 100, y = 70}
dynamic_title = false
# dynamic_padding = true

[font]
normal = {family = "Hack Nerd Font Mono", style = "Regular"}
size = 14

[selection]
save_to_clipboard = true

[terminal]
osc52 = "CopyPaste"
shell = "pwsh"

[mouse]
hide_when_typing = true
bindings = [
{ mouse = "Right", mods = "Control", action = "Paste" },
]

[keyboard]
bindings = [
    # Copy to clipboard (Ctrl + Shift + C)
    { key = "C", mods = "Control|Shift", action = "Copy" },

    # Paste from clipboard (Ctrl + Shift + V)
    { key = "V", mods = "Control", action = "Paste" },

    # Open a new window (Ctrl + Shift + N)
    { key = "N", mods = "Control|Shift", action = "SpawnNewInstance" },

    # Toggle fullscreen (F11)
    { key = "F11", action = "ToggleFullscreen" },

    # Increase Font Size (Ctrl + Plus)
    { key = "Plus", mods = "Control", action = "IncreaseFontSize" },

    # Decrease Font Size (Ctrl + Minus)
    { key = "Minus", mods = "Control", action = "DecreaseFontSize" }
]

[colors]
transparent_background_colors = true

## Theme
# Colors (Dracula+)

[colors.primary]
background = '#282a36'
foreground = '#FFFFFF'

[colors.normal]
black = '#21222C'
red = '#FF5555'
green = '#50FA7B'
yellow = '#FFCB6B'
blue = '#82AAFF'
magenta = '#C792EA'
cyan = '#8BE9FD'
white = '#FFFFFF'

[colors.bright]
black = '#545454'
red = '#FF6E6E'
green = '#69FF94'
yellow = '#FFCB6B'
blue = '#D6ACFF'
magenta = '#FF92DF'
cyan = '#A4FFFF'
white = '#FFFFFF'
